# Generated by Django 5.0.6 on 2024-06-30 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hash', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
