# Generated by Django 4.2.14 on 2024-07-13 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayerProfile', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_hash', models.CharField(max_length=255, unique=True)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
